# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  #vmImage: ubuntu-latest
  name: 'GCP'

jobs:
- job: Job1
  steps:
    - script: echo hello, $HOSTNAME
- job: Job2
  steps:
    - script: echo hello, $HOSTNAME